const now = Date.now();
const day = 86400000;

export const defaultJobs = [
  {
    id: now,
    company: "Google DeepMind",
    role: "Frontend AI Engineer",
    status: "interview",
    location: "Remote",
    source: "manual",
    createdAt: now,
  },
  {
    id: now - day * 1,
    company: "Perplexity",
    role: "React Developer",
    status: "offer",
    location: "San Francisco, CA",
    source: "manual",
    createdAt: now - day * 1,
  },
  {
    id: now - day * 2,
    company: "Pearl Abyss",
    role: "UI/UX Programmer",
    status: "applied",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 2,
  },
  {
    id: now - day * 3,
    company: "xAI",
    role: "Full Stack Engineer",
    status: "applied",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 3,
  },
  {
    id: now - day * 4,
    company: "Zerodha",
    role: "Software Engineer",
    status: "interview",
    location: "Bangalore, India",
    source: "manual",
    createdAt: now - day * 4,
  },
  {
    id: now - day * 5,
    company: "Bungie",
    role: "Systems Programmer",
    status: "rejected",
    location: "Seattle, WA",
    source: "manual",
    createdAt: now - day * 5,
  },
  {
    id: now - day * 6,
    company: "Dhan",
    role: "Frontend Developer",
    status: "applied",
    location: "Mumbai, India",
    source: "manual",
    createdAt: now - day * 6,
  },
  {
    id: now - day * 7,
    company: "Netmarble",
    role: "Backend Engineer",
    status: "applied",
    location: "Seoul, SK",
    source: "manual",
    createdAt: now - day * 7,
  },
  {
    id: now - day * 8,
    company: "UGVCL",
    role: "IT Systems Analyst",
    status: "interview",
    location: "Gujarat, India",
    source: "manual",
    createdAt: now - day * 8,
  },
  {
    id: now - day * 9,
    company: "Spotify",
    role: "Web Developer",
    status: "rejected",
    location: "New York, NY",
    source: "manual",
    createdAt: now - day * 9,
  },
  {
    id: now - day * 10,
    company: "Netflix",
    role: "UI Engineer",
    status: "applied",
    location: "Los Gatos, CA",
    source: "manual",
    createdAt: now - day * 10,
  },
  {
    id: now - day * 11,
    company: "Amazon",
    role: "SDE I",
    status: "interview",
    location: "Seattle, WA",
    source: "manual",
    createdAt: now - day * 11,
  },
  {
    id: now - day * 12,
    company: "Microsoft",
    role: "Frontend Developer",
    status: "offer",
    location: "Redmond, WA",
    source: "manual",
    createdAt: now - day * 12,
  },
  {
    id: now - day * 13,
    company: "Apple",
    role: "React Native Engineer",
    status: "applied",
    location: "Cupertino, CA",
    source: "manual",
    createdAt: now - day * 13,
  },
  {
    id: now - day * 14,
    company: "Meta",
    role: "Software Engineer",
    status: "rejected",
    location: "Menlo Park, CA",
    source: "manual",
    createdAt: now - day * 14,
  },
  {
    id: now - day * 15,
    company: "Stripe",
    role: "Frontend Engineer",
    status: "applied",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 15,
  },
  {
    id: now - day * 16,
    company: "Airbnb",
    role: "Full Stack Developer",
    status: "interview",
    location: "San Francisco, CA",
    source: "manual",
    createdAt: now - day * 16,
  },
  {
    id: now - day * 17,
    company: "Discord",
    role: "Software Engineer",
    status: "applied",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 17,
  },
  {
    id: now - day * 18,
    company: "Uber",
    role: "Web Developer",
    status: "rejected",
    location: "San Francisco, CA",
    source: "manual",
    createdAt: now - day * 18,
  },
  {
    id: now - day * 19,
    company: "Lyft",
    role: "Frontend Engineer",
    status: "applied",
    location: "San Francisco, CA",
    source: "manual",
    createdAt: now - day * 19,
  },
  {
    id: now - day * 20,
    company: "Vercel",
    role: "Next.js Developer",
    status: "interview",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 20,
  },
  {
    id: now - day * 21,
    company: "Supabase",
    role: "Backend Engineer",
    status: "applied",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 21,
  },
  {
    id: now - day * 22,
    company: "Figma",
    role: "UI Engineer",
    status: "interview",
    location: "San Francisco, CA",
    source: "manual",
    createdAt: now - day * 22,
  },
  {
    id: now - day * 23,
    company: "Notion",
    role: "Full Stack Developer",
    status: "offer",
    location: "New York, NY",
    source: "manual",
    createdAt: now - day * 23,
  },
  {
    id: now - day * 24,
    company: "OpenAI",
    role: "Software Engineer",
    status: "applied",
    location: "San Francisco, CA",
    source: "manual",
    createdAt: now - day * 24,
  },
  {
    id: now - day * 25,
    company: "Anthropic",
    role: "AI Integration Engineer",
    status: "rejected",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 25,
  },
  {
    id: now - day * 26,
    company: "Midjourney",
    role: "Frontend Developer",
    status: "applied",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 26,
  },
  {
    id: now - day * 27,
    company: "GitHub",
    role: "Systems Engineer",
    status: "interview",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 27,
  },
  {
    id: now - day * 28,
    company: "GitLab",
    role: "Ruby on Rails Developer",
    status: "rejected",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 28,
  },
  {
    id: now - day * 29,
    company: "Atlassian",
    role: "React Engineer",
    status: "applied",
    location: "Sydney, AUS",
    source: "manual",
    createdAt: now - day * 29,
  },
  {
    id: now - day * 30,
    company: "Canva",
    role: "Graphics Programmer",
    status: "offer",
    location: "Sydney, AUS",
    source: "manual",
    createdAt: now - day * 30,
  },
  {
    id: now - day * 31,
    company: "Shopify",
    role: "Frontend Web Developer",
    status: "interview",
    location: "Toronto, CAN",
    source: "manual",
    createdAt: now - day * 31,
  },
  {
    id: now - day * 32,
    company: "Square",
    role: "Mobile Engineer",
    status: "applied",
    location: "San Francisco, CA",
    source: "manual",
    createdAt: now - day * 32,
  },
  {
    id: now - day * 33,
    company: "Plaid",
    role: "Backend Developer",
    status: "applied",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 33,
  },
  {
    id: now - day * 34,
    company: "Robinhood",
    role: "Software Engineer",
    status: "rejected",
    location: "Menlo Park, CA",
    source: "manual",
    createdAt: now - day * 34,
  },
  {
    id: now - day * 35,
    company: "Coinbase",
    role: "Web3 Developer",
    status: "applied",
    location: "Remote",
    source: "manual",
    createdAt: now - day * 35,
  },
  {
    id: now - day * 36,
    company: "Databricks",
    role: "Data Engineer",
    status: "interview",
    location: "San Francisco, CA",
    source: "manual",
    createdAt: now - day * 36,
  },
  {
    id: now - day * 37,
    company: "Snowflake",
    role: "Cloud Systems Engineer",
    status: "offer",
    location: "Bozeman, MT",
    source: "manual",
    createdAt: now - day * 37,
  },
];
